DROP TABLE IF EXISTS SCR;

DROP TABLE IF EXISTS SCR_ELM;

CREATE TABLE SCR(
	SCR_ID INT AUTO_INCREMENT,
	SCR_NAME VARCHAR(256),
	VERSION INT,
	IS_DELETED INT,
	CREATED_BY VARCHAR(128),
	CREATED_AT DATETIME,
	UPDATED_BY VARCHAR(128),
	UPDATED_AT TIMESTAMP,
	PRIMARY KEY(SCR_ID)
);

CREATE TABLE SCR_ELM(
	SCR_ELM_ID INT AUTO_INCREMENT,
	SERVICE_NAME VARCHAR(256),
	ADAPTER VARCHAR(256),
	PREPARE_INPUT VARCHAR(256),
	SCR_ID INT,
	ORD_IN_GRP INT,
	VERSION INT,
	IS_DELETED INT,
	CREATED_BY VARCHAR(128),
	CREATED_AT DATETIME,
	UPDATED_BY VARCHAR(128),
	UPDATED_AT TIMESTAMP,
	PRIMARY KEY(SCR_ELM_ID)
);

CREATE TABLE IF NOT EXISTS SCR_PRM(
	SCR_PRM_ID INT NOT NULL AUTO_INCREMENT,
	PARAM_KEY VARCHAR(256),
	PARAM_VALUE VARCHAR(256),
	SCR_ID INT,
	ORD_IN_GRP INT,
	VERSION INT,
	IS_DELETED INT,
	CREATED_BY VARCHAR(128),
	CREATED_AT DATETIME,
	UPDATED_BY VARCHAR(128),
	UPDATED_AT TIMESTAMP,
	PRIMARY KEY(SCR_PRM_ID)
);

INSERT INTO SCR(SCR_ID, SCR_NAME, VERSION, IS_DELETED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT) VALUES (1000002, 'DB構成更新', 1, 0, 'data_loader', '2023-09-09 00:00:00', 'data_loader', '2023-09-09 00:00:00');

INSERT INTO SCR_ELM (SCR_ELM_ID, SERVICE_NAME, ADAPTER, PREPARE_INPUT, SCR_ID, ORD_IN_GRP, VERSION, IS_DELETED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT) VALUES (1000011, 'com.remainz.common.service.dbmng.common.UpdateSqlByDefService', '', '', 1000002, 1, 1, 0, 'data_loader', '2023-09-09 00:00:00', 'data_loader', '2023-09-09 00:00:00');
INSERT INTO SCR_ELM (SCR_ELM_ID, SERVICE_NAME, ADAPTER, PREPARE_INPUT, SCR_ID, ORD_IN_GRP, VERSION, IS_DELETED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT) VALUES (1000012, 'com.remainz.common.service.dbmng.common.UpdateSqlByDataService', '', '', 1000002, 2, 1, 0, 'data_loader', '2023-09-09 00:00:00', 'data_loader', '2023-09-09 00:00:00');
INSERT INTO SCR_ELM (SCR_ELM_ID, SERVICE_NAME, ADAPTER, PREPARE_INPUT, SCR_ID, ORD_IN_GRP, VERSION, IS_DELETED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT) VALUES (1000013, 'com.remainz.common.service.dbmng.common.UpdateAllTableService', '', '', 1000002, 3, 1, 0, 'data_loader', '2023-09-09 00:00:00', 'data_loader', '2023-09-09 00:00:00');
