DROP TABLE IF EXISTS TBL_DEF;

CREATE TABLE TBL_DEF(
	TBL_DEF_ID INT NOT NULL AUTO_INCREMENT(1),
	TABLE_NAME VARCHAR(256),
	FIELD_NAME VARCHAR(256),
	TYPE_NAME VARCHAR(256),
	ALLOW_NULL VARCHAR(256),
	KEY_DIV VARCHAR(256),
	DEFAULT_VALUE VARCHAR(256),
	EXTRA VARCHAR(256),
	PRIMARY KEY(TBL_DEF_ID)
);

INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'SCR_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'SCR_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'IS_DELETED', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'CREATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'CREATED_AT', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'UPDATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'UPDATED_AT', 'TIMESTAMP', 'YES', '', null, '');
