/* 以下のSQLは、DBを再構築する場合に使用する。
DROP TABLE IF EXISTS JLDB.GNR_GRP;
DROP TABLE IF EXISTS JLDB.GNR_KEY_VAL;
DROP TABLE IF EXISTS JLDB.ACCNT;
DROP TABLE IF EXISTS JLDB.MAIL;
DROP TABLE IF EXISTS JLDB.SCR;
DROP TABLE IF EXISTS JLDB.SCR_ELM;
*/
