USE JLDB;

CREATE TABLE GNR_GRP(
	GNR_GRP_ID INT AUTO_INCREMENT,
	GNR_GRP_NAME VARCHAR(256),
	VERSION INT,
	IS_DELETED INT,
	CREATED_BY VARCHAR(128),
	CREATED_AT DATETIME,
	UPDATED_BY VARCHAR(128),
	UPDATED_AT TIMESTAMP,
	PRIMARY KEY(GNR_GRP_ID)
);

CREATE TABLE GNR_KEY_VAL(
	GNR_KEY_VAL_ID INT AUTO_INCREMENT,
	GNR_KEY VARCHAR(256),
	GNR_VAL VARCHAR(256),
	GNR_GRP_ID INT,
	ORD_IN_GRP INT,
	VERSION INT,
	IS_DELETED INT,
	CREATED_BY VARCHAR(128),
	CREATED_AT DATETIME,
	UPDATED_BY VARCHAR(128),
	UPDATED_AT TIMESTAMP,
	PRIMARY KEY(GNR_KEY_VAL_ID)
);

CREATE TABLE ACCNT(
	ACCNT_ID INT AUTO_INCREMENT,
	ACCOUNT_NAME VARCHAR(256),
	PASSWORD VARCHAR(256),
	VERSION INT,
	IS_DELETED INT,
	CREATED_BY VARCHAR(128),
	CREATED_AT DATETIME,
	UPDATED_BY VARCHAR(128),
	UPDATED_AT TIMESTAMP,
	PRIMARY KEY(ACCNT_ID)
);

CREATE TABLE IF NOT EXISTS MAIL(
	MAIL_ID INT NOT NULL AUTO_INCREMENT,
	MAIL_FROM VARCHAR(256),
	MAIL_SUBJECT VARCHAR(256),
	SENT_DATE DATETIME,
	HONBUN VARCHAR(8192),
	VERSION INT,
	IS_DELETED INT,
	CREATED_BY VARCHAR(128),
	CREATED_AT DATETIME,
	UPDATED_BY VARCHAR(128),
	UPDATED_AT TIMESTAMP,
	PRIMARY KEY(MAIL_ID)
);

CREATE TABLE SCR(
	SCR_ID INT AUTO_INCREMENT,
	SCR_NAME VARCHAR(256),
	VERSION INT,
	IS_DELETED INT,
	CREATED_BY VARCHAR(128),
	CREATED_AT DATETIME,
	UPDATED_BY VARCHAR(128),
	UPDATED_AT TIMESTAMP,
	PRIMARY KEY(SCR_ID)
);

CREATE TABLE SCR_ELM(
	SCR_ELM_ID INT AUTO_INCREMENT,
	SERVICE_NAME VARCHAR(256),
	ADAPTER VARCHAR(256),
	PREPARE_INPUT VARCHAR(256),
	SCR_ID INT,
	ORD_IN_GRP INT,
	VERSION INT,
	IS_DELETED INT,
	CREATED_BY VARCHAR(128),
	CREATED_AT DATETIME,
	UPDATED_BY VARCHAR(128),
	UPDATED_AT TIMESTAMP,
	PRIMARY KEY(SCR_ELM_ID)
);

SHOW TABLES;
