/* 以下のSQLは、DBを再構築する場合に使用する。
DROP TABLE IF EXISTS REMAINZ_DB.MGNRGRP;
DROP TABLE IF EXISTS REMAINZ_DB.MGNRKEYVAL;
DROP TABLE IF EXISTS REMAINZ_DB.TACCOUNT;
DROP TABLE IF EXISTS REMAINZ_DB.TDICTITEM;
DROP TABLE IF EXISTS REMAINZ_DB.TSCR;
DROP TABLE IF EXISTS REMAINZ_DB.TSCRELM;
*/
