/* 以下のSQLは、DBを再構築する場合に使用する。
DROP TABLE IF EXISTS JLDB.MGNRGRP;
DROP TABLE IF EXISTS JLDB.MGNRKEYVAL;
DROP TABLE IF EXISTS JLDB.TACCOUNT;
DROP TABLE IF EXISTS JLDB.TDICTITEM;
DROP TABLE IF EXISTS JLDB.TSCR;
DROP TABLE IF EXISTS JLDB.TSCRELM;
*/
