DROP TABLE IF EXISTS TBL_DEF;

CREATE TABLE TBL_DEF(
	TBL_DEF_ID INT NOT NULL AUTO_INCREMENT(1),
	TABLE_NAME VARCHAR(256),
	FIELD_NAME VARCHAR(256),
	TYPE_NAME VARCHAR(256),
	ALLOW_NULL VARCHAR(256),
	KEY_DIV VARCHAR(256),
	DEFAULT_VALUE VARCHAR(256),
	EXTRA VARCHAR(256),
	PRIMARY KEY(TBL_DEF_ID)
);

INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_GRP', 'GNR_GRP_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_GRP', 'GNR_GRP_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_GRP', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_GRP', 'IS_DELETED', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_GRP', 'CREATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_GRP', 'CREATED_AT', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_GRP', 'UPDATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_GRP', 'UPDATED_AT', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_KEY_VAL', 'GNR_KEY_VAL_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_KEY_VAL', 'GNR_KEY', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_KEY_VAL', 'GNR_VAL', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_KEY_VAL', 'GNR_GRP_ID', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_KEY_VAL', 'ORD_IN_GRP', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_KEY_VAL', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_KEY_VAL', 'IS_DELETED', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_KEY_VAL', 'CREATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_KEY_VAL', 'CREATED_AT', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_KEY_VAL', 'UPDATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('GNR_KEY_VAL', 'UPDATED_AT', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO TBL_DEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBL_DEF', 'TBL_DEF_ID', 'INT', 'NO', 'PRI', NULL, 'AUTO_INCREMENT');
INSERT INTO TBL_DEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBL_DEF', 'TABLE_NAME', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO TBL_DEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBL_DEF', 'FIELD_NAME', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO TBL_DEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBL_DEF', 'TYPE_NAME', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO TBL_DEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBL_DEF', 'ALLOW_NULL', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO TBL_DEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBL_DEF', 'KEY_DIV', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO TBL_DEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBL_DEF', 'DEFAULT_VALUE', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO TBL_DEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBL_DEF', 'EXTRA', 'VARCHAR(256)', 'YES', '', NULL, '');

INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('ACCNT', 'ACCNT_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('ACCNT', 'ACCOUNT_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('ACCNT', 'PASSWORD', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('ACCNT', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('ACCNT', 'IS_DELETED', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('ACCNT', 'CREATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('ACCNT', 'CREATED_AT', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('ACCNT', 'UPDATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('ACCNT', 'UPDATED_AT', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MAIL', 'MAIL_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MAIL', 'MAIL_FROM', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MAIL', 'MAIL_SUBJECT', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MAIL', 'SENT_DATE', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MAIL', 'HONBUN', 'VARCHAR(8192)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MAIL', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MAIL', 'IS_DELETED', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MAIL', 'CREATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MAIL', 'CREATED_AT', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MAIL', 'UPDATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MAIL', 'UPDATED_AT', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'SCR_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'SCR_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'IS_DELETED', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'CREATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'CREATED_AT', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'UPDATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR', 'UPDATED_AT', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR_ELM', 'SCR_ELM_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR_ELM', 'SERVICE_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR_ELM', 'ADAPTER', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR_ELM', 'PREPARE_INPUT', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR_ELM', 'SCR_ID', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR_ELM', 'ORD_IN_GRP', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR_ELM', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR_ELM', 'IS_DELETED', 'INT', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR_ELM', 'CREATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR_ELM', 'CREATED_AT', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR_ELM', 'UPDATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBL_DEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('SCR_ELM', 'UPDATED_AT', 'TIMESTAMP', 'YES', '', null, '');
